/**
 * ModelKit Feature IDs
 * Auto-generated by ModelKit
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run `npx modelkit-generate --api-url <url>` to regenerate
 *
 * Found 3 features
 */

export type FeatureId =
  | "discoverCompetitors"
  | "generate_competitor_analysis"
  | "refineContent";

