#!/usr/bin/env node

/**
 * ModelKit Type Generator
 * Fetches features from your ModelKit API and generates TypeScript types
 */

import * as fs from "fs";
import * as path from "path";

interface Feature {
  featureId: string;
  override: {
    modelId: string;
    temperature?: number;
    maxTokens?: number;
    topP?: number;
    topK?: number;
    updatedAt?: number;
  };
}

async function fetchFeatures(apiUrl: string): Promise<Feature[]> {
  try {
    const response = await fetch(`${apiUrl}/overrides`);

    if (!response.ok) {
      throw new Error(
        `API returned ${response.status}: ${response.statusText}`
      );
    }

    const data = (await response.json()) as Feature[];

    if (!data || !Array.isArray(data)) {
      throw new Error("Invalid API response format");
    }

    return data;
  } catch (error) {
    throw new Error(
      `Failed to fetch features: ${
        error instanceof Error ? error.message : String(error)
      }`
    );
  }
}

function generateTypeFile(features: Feature[]): string {
  if (features.length === 0) {
    return `/**
 * ModelKit Feature IDs
 * Auto-generated by ModelKit
 *
 * No features found.
 * Make sure your ModelKit instance has features configured.
 */

export type FeatureId = string;
`;
  }

  const sortedIds = features.map((f) => f.featureId).sort();
  const typeUnion = sortedIds.map((id) => `  | "${id}"`).join("\n");

  return `/**
 * ModelKit Feature IDs
 * Auto-generated by ModelKit
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Run \`npx modelkit-generate --api-url <url>\` to regenerate
 *
 * Found ${features.length} feature${features.length === 1 ? "" : "s"}
 */

export type FeatureId =
${typeUnion};

`;
}

async function main() {
  const args = process.argv.slice(2);

  // Parse arguments
  let apiUrl = "";
  let outputPath = "src/modelkit.generated.ts";

  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--api-url" && args[i + 1]) {
      apiUrl = args[i + 1];
      i++;
    } else if (args[i] === "--output" && args[i + 1]) {
      outputPath = args[i + 1];
      i++;
    } else if (args[i] === "--help" || args[i] === "-h") {
      console.log(`
ModelKit Type Generator

Usage:
  npx modelkit-generate --api-url <url> [options]

Options:
  --api-url <url>      ModelKit API endpoint URL (required)
  --output <path>      Output file path (default: src/modelkit.generated.ts)
  --help, -h           Show this help message

Example:
  npx modelkit-generate --api-url http://localhost:3000/api/modelkit
      `);
      process.exit(0);
    }
  }

  if (!apiUrl) {
    console.error("❌ Error: --api-url is required\n");
    console.log("Usage: npx modelkit-generate --api-url <url>");
    console.log(
      "Example: npx modelkit-generate --api-url http://localhost:3000/api/modelkit"
    );
    process.exit(1);
  }

  try {
    console.log("🔍 Fetching features from ModelKit API...\n");
    console.log(`   API URL: ${apiUrl}\n`);

    const features = await fetchFeatures(apiUrl);

    if (features.length === 0) {
      console.log("⚠️  No features found");
      console.log(
        "   Make sure your ModelKit instance has features configured\n"
      );
    } else {
      console.log(
        `✅ Found ${features.length} feature${
          features.length === 1 ? "" : "s"
        }:\n`
      );
      features.slice(0, 5).forEach((f) => {
        console.log(`   • ${f.featureId} → ${f.override.modelId}`);
      });
      if (features.length > 5) {
        console.log(`   ... and ${features.length - 5} more`);
      }
      console.log();
    }

    const content = generateTypeFile(features);
    const outputDir = path.dirname(outputPath);

    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, content);
    console.log(`✅ Generated types at ${outputPath}`);
    console.log(
      `\n💡 Import with: import type { FeatureId } from "./${path
        .basename(outputPath)
        .replace(/\.ts$/, "")}";`
    );
  } catch (error) {
    console.error(
      "❌ Error:",
      error instanceof Error ? error.message : String(error)
    );
    process.exit(1);
  }
}

main();
